# Unified Application Configuration
application:
  name: DevOpsSimulator
  versions:
    production: 1.0.0
    development: 2.0.0-beta
    experimental: 3.0.0-experimental

environments:
  production:
    server:
      host: 0.0.0.0
      port: 8080
      ssl_enabled: true
    database:
      host: prod-db.example.com
      name: devops_prod
    features:
      auto_scaling: true
      backup_enabled: true

  development:
    server:
      host: localhost
      port: 3000
      ssl_enabled: false
    database:
      host: localhost
      name: devops_dev
    features:
      experimental_features: true

  experimental:
    server:
      host: 0.0.0.0
      port: 9000
      ssl_enabled: true
    database:
      host: cluster.example.com
      name: devops_experimental
      distributed: true
    ai_features:
      predictive_scaling: true
      anomaly_detection: true
      auto_optimization: true
      feature_flag: true

